### ISSUE TITLE
Request for Snap and/or Flatpak release

### ISSUE THREAD

**Issue by MariusVB** [TablePlus/TablePlus-Linux#17]
Why not focus on a Snap package? You will reach Ubuntu and almost any other Linux distro.

At least put it on the roadmap.

**Comment by maniadevice** [comment]
+1 for Flatpak. I've had more success with Flatpaks than Snaps. Not sure if things have improved in the snap world, lately. Also, I'm sure more distros provide first class support for Flatpaks instead of Snaps (Mint, Elementary)

**Comment by nblackburn** [comment]
I think Flatpak is the better option as it is getting 1st class support in several distributions.

https://flatpak.org
https://flathub.org

**Comment by eberkund** [comment]
This would fix #25 and #28 also

I've created many snap packages and could provide some assistance if necessary

**Comment by dvkndn** [comment]
Thank you all! We are focusing on the basic features at the moment, but rest assured that we do want to distribute to as many distro as possible. We will see the options and update here.

Thank you @eberkund , we're more than happy to hear that

**Comment by divoxx** [comment]
I'd also vote for flatpak over snap. A lot more distributions support flatpak, and it also doesn't require systemd (as I believe snap does).

Thanks for the hard work on this!

**Comment by wastrachan** [comment]
I'm sure this thread is going to get noisy quickly-- but I'd like to offer one more alternative for you to consider: Appimage. 

Unlike snap _or_ flatpack, it's an option that lets you target _at least_ seven major distros, and it's the only option that does not require your users to require supporting libraries or daemons. Appimages behave a lot like the packaging you're familiar with on MacOS-- a single file that you can copy out of an archive and run. Nothing extra to install or maintain. 

For both flatpack and snap, your user will have to have one or both supporting packages installed, and _then_ they'll have to download your binaries and install them as well.

As for your build pipeline-- you'd normally package an Appimage directly from source when you build, so you need some pretty minor additions to your makefile or shell script, and an appimage to handle building the appimage. 

If I can't win you over, I think my second vote would be flatpack. I've found snaps to be incredibly frustrating, and flatpacks for me have struck the best balance between "I have to install a helper application" and Snaps' "this is just a different take on a package manager". 

You might find this comparison table helpful as you consider the options: https://github.com/AppImage/AppImageKit/wiki/Similar-projects#comparison

And of course, I'll continue to help maintain the Arch PKGBUILD as long as you need!

**Comment by nahuelwexd** [comment]
I opt for a Flatpak package over Snap or AppImage.

Flatpak comes pre-installed on many distros (when Snap comes only on Ubuntu, Zorin, and Solus), and allows you to run the application in a truly host-isolated environment. It also incorporates the SDK concept, where you have a set of ready-to-use libraries and they are exactly the same libraries that the user will end up using, so if it "works on my machine" it also works on the user's.

When distributing a Flatpak package, you can choose various solutions: distribute on Flathub, the central Flatpaks repository, create your own repository for your application or simply distribute the .flatpak files separately. Unlike the Snap Store, Flathub is not tied to the whims of any company, but is fully community-managed, and already provides all the necessary infrastructure to publish and update your app with no extra effort.

Flatpak also incorporates the concept of "extensions", which allows offering optional packages for your application that the user can install whenever they want in a simple and secure way. These extensions can also be distributed via Flathub, saving you from implementing an extension installation system for your app.

With all this said, I hope soon to be able to find a Flatpak Table Plus package to be able to install it on my system :smile:

**Comment by Merazi** [comment]
Another vote for flatpak.
Flatpak is easier to develop with and it's available in more distributions.

**Comment by Wulfheart** [comment]
Is there any change of status?

**Comment by ProjectInfinity** [comment]
Seems like TablePlus for Linux is pretty abandoned.

**Comment by wastrachan** [comment]
> Seems like TablePlus for Linux is pretty abandoned.

It was last updated days ago. How do you justify that comment?

**Comment by huyphams** [comment]
We just released an update on 27 April 2021 (6 days ago) https://tableplus.com/linux/changelog 
@wastrachan

**Comment by ProjectInfinity** [comment]
> > Seems like TablePlus for Linux is pretty abandoned.
> 
> It was last updated days ago. How do you justify that comment?

Because since 2019, we have not seen a significant amount of work come to fruition. I used to use TablePlus on Mac and would always recommend it to everyone. On Mac it is a great piece of software and Linux sorely needs a highly polished client but for some reason it seems like with the linux edition they just decided to start from scratch. That may not be the case but it's been years and there's still a lack of basic functionality.

Additionally only **Ubuntu** is supported. That's not a good move. At the very least AppImages should be supported to allow everyone to test out the alpha, this is what AppImages are for.
As of "recent" you cannot even run TablePlus on ArchLinux because it is compiled against too old libraries.

> We just released an update on 27 April 2021 (6 days ago) https://tableplus.com/linux/changelog

Can you maybe explain the process here? If I were to read the changelogs it doesn't seem like much has happened since 2019. Is nothing being ported over from the Mac edition? 
What about shipping a universally accepted format so we don't have to extract a deb package in order to run the software on modern Linux operating systems and hope to god that Ubuntu doesn't require you to build against ancient libraries.

Setting up a AppImage (usually preferred method), flatpak or even god forbid a snap is not a time consuming thing to do and benefits everyone.

**Comment by huyphams** [comment]
It could not be slow development but it's not abandoned, they are different, we always ask users which are their priority features so we can bring them to Linux. We choose Ubuntu because it is widely used by the users and we see a lot of users who uses Arch can install the app as well, via https://aur.archlinux.org/packages/tableplus/ (I'm one of the maintainer)

I can say that TablePlus has most of the basic functions that are needed for daily use (not all users). Again, it could be slow development but we will keep update it until it has a stable release. (The Windows version takes 2 years of development, the macOS 3 years old now).

**Comment by huyphams** [comment]
We will bring TablePlus to more platforms next month and release the beta version as the app has almost all basic features.

![linux_beta](https://user-images.githubusercontent.com/3654622/130251561-c2833af6-d497-4765-bd3d-d03e70c07d6b.png)

**Comment by krekas** [comment]
> We will bring TablePlus to more platforms next month and release the beta version as the app has almost all basic features.
> 

It's been more than 6 months and seams there's no release for other platforms. Just make flatpak version please.

**Comment by Wulfheart** [comment]
@krekas 

> We will bring TablePlus to more platforms next month and release the beta version as the app has almost all basic features.

![grafik](https://user-images.githubusercontent.com/25671390/160830545-c0aa6425-4f5f-4484-b90f-6a8931e78b22.png)

**Comment by huyphams** [comment]
I'm sorry guys, I just released 186 a few minutes ago, but still no flatpak :(
![107768897_1660277687458056_1574561900102018542_n](https://user-images.githubusercontent.com/3654622/160831366-978cb1f1-8b03-4706-a3c0-5eaaa3781491.jpeg)

**Comment by 0rax** [comment]
Seems like the arch AUR packages is currently broken due to a specific dependency version that is not present by default.

I've read most of the idea thrown around here and as most have echoed here, snap might not be the best idea here has it has mainly been only adopted by Ubuntu based distribution (which are already covered by the current package). Flatpak is interesting as it can provide process isolation by itself but is another barrier to entry for someone that wants to test TablePlus without having to run a complete new runtime.

The real issue I see with the current releases is that dependencies tends to break easily when the Ubuntu package is uncompressed on another system. Having a self-contained executable that includes all those using an AppImage would fix this issue, allow a lot more people to have access to it. It would also be a good step in understanding what are the real dependencies that requires to be packed for future releases as FlatPak or Snaps.

**Comment by krekas** [comment]
So will there be AppImage or Flatpak?

**Comment by huyphams** [comment]
Please follow this issue: https://github.com/TablePlus/TablePlus-Linux/issues/149
